### ISSUE TITLE
On desugaring before/during type checking

### ISSUE THREAD

**Issue by Hirrolot** [brendanzab/language-garden#1]
Hi, thank you for your great code examples with nice documentation. One thing I was wondering when looking into `elab-dependent` is that we could instead perform desugaring _before_ the actual type checking; for example, it seems that you have a list of function parameters that are desugared by the elaborator (type checker) into curried single-argument functions. However, the downside is that the type checker becomes quite involved even for this simplistic type theory without fancy extensions, such as unification or subtyping.

Is there any real example that desugaring _during_ type checking is preferred? We could desugar some syntactic forms beforehand (e.g., during parsing or shortly before feeding the surface syntax to the type checker) and gain drastic simplification of the type system implementation.

**Comment by brendanzab** [comment]
Hey, sorry for the belated response. One advantage of this is that we can produce user-friendly error messages that are more directly related to what the user originally wrote. But you are right that it can make things rather involved. One approach to trying to separate some of the concerns is to move some of the elaboration into a “refiner”, as seen in  [dreamtt], [cooltt], [TeenyTT] and [MicroTT] (inspired partly by [Atkey’s Algebraic Type Checking](https://bentnib.org/posts/2015-04-19-algebraic-approach-typechecking-and-elaboration.html)) – but then I have some questions about how to make the errors more user friendly again.


[dreamtt]: https://github.com/jonsterling/dreamtt
[cooltt]: https://github.com/RedPRL/cooltt
[TeenyTT]: https://github.com/TOTBWF/teenytt
[MicroTT]: https://gist.github.com/TOTBWF/9b2c071d2edb1c6596b785656c866fd6

**Comment by Hirrolot** [comment]
Could you provide an example of a user-friendly error message, e.g., in the case of a multi-parameter function type? (Thanks for the links by the way, will have a look into them.)

**Comment by brendanzab** [comment]
Ah not sure with regards to functions… I guess I was thinking more in the general case of desugaring - like desugaring `while` loops to `loop` loops in Rust - you’d rather it talk about the `while` loop, not the desugared form - for example if you have a type error somewhere. This is kind of a general principle I try to keep with my surface syntax/core syntax distinction. The surface syntax can almost be seen as a parse tree, close to what the programmer originally wrote. Feel free to disagree with that choice, however!

**Comment by Hirrolot** [comment]
I see. In my language, I have a bit different approach:
 - I _desugar_ certain forms of surface syntax during parsing, such as multi-parameter functions, so the parser acts as a syntax elaborator from surface syntax to core syntax. This also includes converting named variables to De Bruijn indices.
 - I _sugar_ certain forms of core syntax back during pretty-printing. For example, my pretty-printer recognizes `\x -> \y -> x` as a multi-parameter function and outputs `\x, y -> x`, as expected.

With this scheme, I don't have to deal with surface syntax during type-checking, at the same time being able to report to a user what they originally wrote. (This also has an interesting implication that the function composition of parsing and pretty-printing acts as a code formatter.) The bidirectional type-checker for a dependent lambda calculus (roughly CoC + `let`) is thus ~90 LoC.

I see that your approach is adopted in other projects though, such as the celebrated `elaboration-zoo`, so I asked.

**Comment by brendanzab** [comment]
Yeah, generally with this approach you’d have a “distiller” or “elaborator” that goes from core terms to surface terms, adding back the sugar as needed. But that can be an involved process – and if the desire is extreme brevity then moving desugaring into the parser is probably the way to go.

**Comment by Hirrolot** [comment]
Mini-TT also [desugars during parsing](https://www.cse.chalmers.se/research/group/logic/Mini-TT/Core.cf) (it's quite neat that their parser generator provides a means to define sugar lol). But it doesn't perform sugaring in the pretty-printer AFAICT.

Anyway, thanks for your reply, and all the good luck in investigating type theory!
